/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.HangHoaDAO;
import DTO.HangHoa;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import Main.FontOptionPane;

/**
 *
 * @author Admin
 */
public class HangHoaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HangHoaJPanel
     */
    ArrayList<HangHoa> listHH;

    public HangHoaJPanel() {
        initComponents();
        FontOptionPane.setUIFont();
    }

    void LoadHHVaoTable(JTable jt, JPanel jpn, JScrollPane jsp, int trangthai) {
        String[] header = {"Mã hàng hóa", "Mã nhóm hàng", "Mã nhà cung cấp", "Tên hàng hóa", "DVT", "Giá bán", "Hệ số", "Giá nhập", "Hình Ảnh", "Số lượng tồn", "Trạng thái"};
        if (jt == null && jpn == null && jsp == null) {
            jt = jtHangHoa;
            jpn = jpnView;
            jsp = jspHangHoa;
        }
        listHH = HangHoaDAO.getInstance().getListHangHoa(trangthai);
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 10 ? Boolean.class : String.class;
            }
        };

        for (HangHoa hh : listHH) {
            Object[] row = {hh.getMaHang(), hh.getMaNhomHang(), hh.getMaNCC(), hh.getTenHang(), hh.getdVT(), hh.getGiaBan(), hh.getHeSo(), hh.getGiaNhap(), hh.getHinhAnh(), hh.getSoLuongTon(), hh.getTrangThai()};
            modelTableDb.addRow(row);
        }

        TableRowSorter<TableModel> rowSorter = null;

        jt.setModel(modelTableDb);
        jt.setRowSorter(rowSorter);

        jt.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jt.setFont(new Font("Arial", Font.PLAIN, 14));
        jt.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jt.setRowHeight(50);
        jt.validate();
        jt.repaint();

        jsp.setPreferredSize(new Dimension(1350, 400));

        jpn.removeAll();
        jpn.setLayout(new CardLayout());
        jpn.add(jsp);
        jpn.validate();
        jpn.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbQuanLyHH = new javax.swing.JTabbedPane();
        jpnQuanLyHH = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        jpnView = new javax.swing.JPanel();
        jspHangHoa = new javax.swing.JScrollPane();
        jtHangHoa = new javax.swing.JTable();
        jpnKhoiPhucHH = new javax.swing.JPanel();
        btnKhoiPhuc = new javax.swing.JButton();
        btnXoaVinhVien = new javax.swing.JButton();
        jpnViewKhoiPhuc = new javax.swing.JPanel();
        jspHangHoaKhoiPhuc = new javax.swing.JScrollPane();
        jtHangHoaKhoiPhuc = new javax.swing.JTable();

        jtbQuanLyHH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtbQuanLyHH.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbQuanLyHHStateChanged(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-plus.png"))); // NOI18N
        btnThem.setText("Thêm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHangHoaMouseClicked(evt);
            }
        });
        jspHangHoa.setViewportView(jtHangHoa);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jspHangHoa)
                .addGap(0, 0, 0))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnQuanLyHHLayout = new javax.swing.GroupLayout(jpnQuanLyHH);
        jpnQuanLyHH.setLayout(jpnQuanLyHHLayout);
        jpnQuanLyHHLayout.setHorizontalGroup(
            jpnQuanLyHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyHHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnQuanLyHHLayout.createSequentialGroup()
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnQuanLyHHLayout.setVerticalGroup(
            jpnQuanLyHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyHHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbQuanLyHH.addTab("Quản lý hàng hóa", jpnQuanLyHH);

        btnKhoiPhuc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnKhoiPhuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-recycling.png"))); // NOI18N
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        btnXoaVinhVien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXoaVinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-delete-forever.png"))); // NOI18N
        btnXoaVinhVien.setText("Xóa vĩnh viễn");
        btnXoaVinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaVinhVienActionPerformed(evt);
            }
        });

        jtHangHoaKhoiPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspHangHoaKhoiPhuc.setViewportView(jtHangHoaKhoiPhuc);

        javax.swing.GroupLayout jpnViewKhoiPhucLayout = new javax.swing.GroupLayout(jpnViewKhoiPhuc);
        jpnViewKhoiPhuc.setLayout(jpnViewKhoiPhucLayout);
        jpnViewKhoiPhucLayout.setHorizontalGroup(
            jpnViewKhoiPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewKhoiPhucLayout.createSequentialGroup()
                .addComponent(jspHangHoaKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnViewKhoiPhucLayout.setVerticalGroup(
            jpnViewKhoiPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspHangHoaKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnKhoiPhucHHLayout = new javax.swing.GroupLayout(jpnKhoiPhucHH);
        jpnKhoiPhucHH.setLayout(jpnKhoiPhucHHLayout);
        jpnKhoiPhucHHLayout.setHorizontalGroup(
            jpnKhoiPhucHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoiPhucHHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnKhoiPhucHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnViewKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnKhoiPhucHHLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoaVinhVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnKhoiPhucHHLayout.setVerticalGroup(
            jpnKhoiPhucHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhoiPhucHHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnKhoiPhucHHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaVinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jpnViewKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbQuanLyHH.addTab("Khôi phục hàng hóa", jpnKhoiPhucHH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbQuanLyHH)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbQuanLyHH)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jtHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHangHoaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && jtHangHoa.getSelectedRow() != -1) {
            int index = jtHangHoa.getSelectedRow();

            HangHoa hangHoa = listHH.get(index);

            HangHoaJFrame frame = new HangHoaJFrame(hangHoa, this, 0);
            frame.setResizable(false);

            JDialog dialog = new JDialog();
            dialog.setModal(true);
            dialog.getContentPane().add(frame.getContentPane());
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setTitle("Sửa hàng hóa");
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jtHangHoaMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        HangHoaJFrame frame = new HangHoaJFrame(null, this, 1);
        frame.setResizable(false);

        JDialog dialog = new JDialog();
        dialog.setModal(true);
        dialog.getContentPane().add(frame.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setTitle("Thêm hàng hóa");
        dialog.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int index = jtHangHoa.getSelectedRow();
            HangHoa hangHoa = listHH.get(index);

            int maHang = hangHoa.getMaHang();
            String tenHang = hangHoa.getTenHang();

            int kq = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa hàng hóa có tên là: " + tenHang + "?", "Câu hỏi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kq == JOptionPane.YES_OPTION) {
                HangHoaDAO.getInstance().deleteHangHoa(maHang);
            }
            listHH.remove(index);
            LoadHHVaoTable(jtHangHoa, jpnView, jspHangHoa, 1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng hóa muốn xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        // TODO add your handling code here:
        try {
            int index = jtHangHoaKhoiPhuc.getSelectedRow();

            HangHoa hangHoa = listHH.get(index);

            HangHoaDAO.getInstance().recoveryHangHoa(hangHoa.getMaHang());

            listHH.remove(index);
            LoadHHVaoTable(jtHangHoaKhoiPhuc, jpnViewKhoiPhuc, jspHangHoaKhoiPhuc, 0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng hóa muốn khôi phục!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void btnXoaVinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaVinhVienActionPerformed
        // TODO add your handling code here:
        try {
            int index = jtHangHoaKhoiPhuc.getSelectedRow();

            HangHoa hangHoa = listHH.get(index);

            int maHang = hangHoa.getMaHang();
            String tenHang = hangHoa.getTenHang();

            int kq = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa vĩnh viễn hàng hóa có tên là: " + tenHang + "?", "Câu hỏi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kq == JOptionPane.YES_OPTION) {
                HangHoaDAO.getInstance().deletePermanentHangHoa(maHang);
            }
            listHH.remove(index);
            LoadHHVaoTable(jtHangHoaKhoiPhuc, jpnViewKhoiPhuc, jspHangHoaKhoiPhuc, 0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng hóa muốn xóa vĩnh viễn!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnXoaVinhVienActionPerformed

    private void jtbQuanLyHHStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbQuanLyHHStateChanged
        // TODO add your handling code here:
        int index = jtbQuanLyHH.getSelectedIndex();
        if (index == 0) {
            LoadHHVaoTable(jtHangHoa, jpnView, jspHangHoa, 1);
        } else {
            LoadHHVaoTable(jtHangHoaKhoiPhuc, jpnViewKhoiPhuc, jspHangHoaKhoiPhuc, 0);
        }
    }//GEN-LAST:event_jtbQuanLyHHStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaVinhVien;
    private javax.swing.JPanel jpnKhoiPhucHH;
    private javax.swing.JPanel jpnQuanLyHH;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnViewKhoiPhuc;
    private javax.swing.JScrollPane jspHangHoa;
    private javax.swing.JScrollPane jspHangHoaKhoiPhuc;
    private javax.swing.JTable jtHangHoa;
    private javax.swing.JTable jtHangHoaKhoiPhuc;
    private javax.swing.JTabbedPane jtbQuanLyHH;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
