/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.NhaCungCapDAO;
import DTO.NhaCungCap;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class NhaCungCapJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCapJPanel
     */
    public NhaCungCapJPanel() {
        initComponents();
        LoadNCCVaoTable();
    }
    ArrayList<NhaCungCap> listNCC = NhaCungCapDAO.getInstance().getListNhaCungCap();
    void LoadNCCVaoTable() {
        String[] header = {"Mã nhà cung cấp", "Tên nhà cung cấp", "SDT", "Địa chỉ", "Trạng thái"};
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 10 ? Boolean.class : String.class;
            }
        };

        for (NhaCungCap ncc : listNCC) {
            Object[] row = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getSDT(), ncc.getDiaChi(), ncc.getTrangThai()};
            modelTableDb.addRow(row);
        }

        TableRowSorter<TableModel> rowSorter = null;

        jtNhaCungCap.setModel(modelTableDb);
        jtNhaCungCap.setRowSorter(rowSorter);

        jtNhaCungCap.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jtNhaCungCap.setFont(new Font("Arial", Font.PLAIN, 14));
        jtNhaCungCap.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jtNhaCungCap.setRowHeight(50);
        jtNhaCungCap.validate();
        jtNhaCungCap.repaint();

        jspNhaCungCap.setPreferredSize(new Dimension(1350, 400));

        jpnView.removeAll();
        jpnView.setLayout(new CardLayout());
        jpnView.add(jspNhaCungCap);
        jpnView.validate();
        jpnView.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSearch = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();
        jspNhaCungCap = new javax.swing.JScrollPane();
        jtNhaCungCap = new javax.swing.JTable();

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnThem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-plus.png"))); // NOI18N
        btnThem.setText("Thêm mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jtNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNhaCungCapMouseClicked(evt);
            }
        });
        jspNhaCungCap.setViewportView(jtNhaCungCap);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspNhaCungCap)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    int flag = 0;
    NhaCungCapJFrame frame = null;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (frame != null) {
            if (frame.isDisplayable()) {
                flag = 1;
                LoadNCCVaoTable();
            } else {
                flag = 0;
            }
        }
        if (flag == 0) {
            frame = new NhaCungCapJFrame(null, 1);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setTitle("Thông tin nhà cung cấp");
            frame.setVisible(true);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void jtNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNhaCungCapMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && jtNhaCungCap.getSelectedRow() != -1) {
            if (frame != null) {
                if (frame.isDisplayable()) {
                    flag = 1;
                } else {
                    flag = 0;
                }
            }
            if (flag == 0) {
                int index = jtNhaCungCap.getSelectedRow();

                NhaCungCap ncc = listNCC.get(index);

                frame = new NhaCungCapJFrame(ncc, 0);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setTitle("Thông tin nhà cung cấp");
                frame.setVisible(true);
                if(frame.isDisplayable()) {
                    listNCC = NhaCungCapDAO.getInstance().getListNhaCungCap();
                    LoadNCCVaoTable();
                }
            }
        }
    }//GEN-LAST:event_jtNhaCungCapMouseClicked

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JPanel jpnView;
    private javax.swing.JScrollPane jspNhaCungCap;
    private javax.swing.JTable jtNhaCungCap;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
