CREATE TABLE hanghoa (
  MaHang NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  MaNhomHang NUMBER NOT NULL,
  MaNCC NUMBER NOT NULL,
  TenHang NVARCHAR2(50) NOT NULL,
  DVT NVARCHAR2(30) DEFAULT 'Chưa xác định',
  GiaBan FLOAT DEFAULT 0,
  HeSo FLOAT DEFAULT 1.2,
  GiaNhap FLOAT NOT NULL,
  HinhAnh NVARCHAR2(50) DEFAULT 'Chưa xác định',
  SoLuongTon FLOAT DEFAULT 0,
  TrangThai NUMBER DEFAULT 1
);

CREATE OR REPLACE TRIGGER insert_giaban
BEFORE INSERT ON hanghoa
FOR EACH ROW
BEGIN
    :NEW.GiaBan := :NEW.GiaNhap * :NEW.HeSo;
END;
/

CREATE OR REPLACE TRIGGER update_giaban
BEFORE UPDATE ON hanghoa
FOR EACH ROW
BEGIN
    IF UPDATING('GiaNhap') OR UPDATING('HeSo') THEN
        :NEW.GiaBan := :NEW.GiaNhap * :NEW.HeSo;
    END IF;
END;
/

INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 1, N'Chuối già Nam Mỹ', N'Kg', 1.2, 25000, 'chuoiGia.jpg', 16.5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 2, N'Dưa hấu đỏ', N'Kg', 1.2, 12500, 'duaHauDo.jpg', 15);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 1, N'Dưa lưới', N'Kg', 1.2, 45000, 'duaLuoi.jpg', 20);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 2, N'Cam vàng nội địa Trung', N'Kg', 1.2, 40000, 'camVang.jpg', 20.5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 3, N'Nho xanh Nam Phi', N'Kg', 1.2, 125000, 'nhoXanh.jpg', 10.5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 4, N'Quýt giống Úc', N'Kg', 1.2, 40000, 'quytUc.jpg', 12.5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 3, N'Cam sành', N'Kg', 1.2, 12500, 'camSanh.jpg', 23);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 5, N'Táo Autumn Mỹ', N'Kg', 1.2, 57500, 'taoMy.jpg', 8);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (4, 5, N'Ổi Đài Loan', N'Kg', 1.2, 17500, 'oiDaiLoan.jpg', 6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 1, N'Cải bẹ xanh', N'Kg', 1.2, 15000, 'caiBeXanh.jpg', 9);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 1, N'Cải ngọt', N'Kg', 1.2, 15000, 'caiNgot.jpg', 6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 2, N'Cải thìa', N'Kg', 1.2, 15000, 'caiThia.jpg', 11);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 3, N'Cải bẹ dún', N'Kg', 1.2, 15000, 'caiBeDun.jpg', 9);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 3, N'Rau dền', N'Kg', 1.2, 12500, 'rauDen.jpg', 12);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 2, N'Rau lang', N'Kg', 1.2, 15000, 'rauLang.jpg', 14);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 4, N'Rau mồng tơi', N'Kg', 1.2, 12500, 'rauMongToi.jpg', 10.5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 5, N'Rau muống nước', N'Kg', 1.2, 7500, 'rauMuongNuoc.jpg', 13);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 5, N'Rau ngót', N'Kg', 1.2, 15000, 'rauNgot.jpg', 5.2);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (1, 4, N'Rau tần ô', N'Kg', 1.2, 22500, 'rauTanO.jpg', 6.6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 1, N'Khoai lang Nhật', N'Kg', 1.2, 15000, 'khoaiLangNhat.jpg', 7);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 2, N'Bí đỏ hột lộ', N'Kg', 1.2, 12500, 'biDoHoLo.jpg', 12);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 1, N'Bí xanh', N'Kg', 1.2, 22500, 'biXanh.jpg', 7);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 2, N'Cà chua', N'Kg', 1.2, 20000, 'caChua.jpg', 12);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 3, N'Cà rốt', N'Kg', 1.2, 17500, 'caRot.jpg', 9);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 3, N'Khoai tây', N'Kg', 1.2, 25000, 'khoaiTay.jpg', 15);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 4, N'Củ cải trắng', N'Kg', 1.2, 15000, 'cuCaiTrang.jpg', 6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 5, N'Củ đậu', N'Kg', 1.2, 25000, 'cuDen.jpg', 9);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 5, N'Khoai mỡ', N'Kg', 1.2, 25000, 'khoaiMo.jpg', 10);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (2, 4, N'Ớt chuông', N'Kg', 1.2, 17500, 'otChuong.jpg', 8);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm hương', N'Kg', 1.2, 190000, 'namHuong.jpg', 6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 4, N'Nấm bào ngư trắng', N'Kg', 1.2, 190000, 'namBaoNguTrang.jpg', 5);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm kim châm', N'Kg', 1.2, 190000, 'namKimCham.jpg', 7);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 4, N'Nấm mối đen', N'Kg', 1.2, 190000, 'namMoiDen.jpg', 4);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm linh chi nâu', N'Kg', 1.2, 185000, 'namLinhChi.jpg', 6);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 4, N'Nấm đùi gà', N'Kg', 1.2, 185000, 'namDuiGa.jpg', 3);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm rơm', N'Kg', 1.2, 100000, 'namRom.jpg', 10);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 4, N'Nấm Notaly', N'Kg', 1.2, 190000, 'namNotaly.jpg', 4);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm tuyết', N'Kg', 1.2, 500000, 'namTuyet.jpg', 3);
INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, HeSo, GiaNhap, HinhAnh, SoLuongTon) VALUES (3, 5, N'Nấm mỡ nâu', N'Kg', 1.2, 290000, 'namMoNau.jpg', 7);

CREATE TABLE hoadon (
  MaHD NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  MaNV NUMBER NOT NULL,
  MaKH NUMBER,
  NgayTao DATE DEFAULT SYSDATE,
  TongTien FLOAT DEFAULT 0,
  TrangThai NVARCHAR2(50) DEFAULT 'Đã hoàn thành'
);

INSERT    INTO hoadon (MaNV, MaKH, TongTien) VALUES (1, 1, 0);
INSERT    INTO hoadon (MaNV, MaKH, TongTien) VALUES (2, 2, 0);
INSERT    INTO hoadon (MaNV, MaKH, TongTien) VALUES (3, 3, 0);
INSERT    INTO hoadon (MaNV, MaKH, TongTien) VALUES (3, NULL, 0);

CREATE TABLE chitiethoadon (
  MaHang NUMBER NOT NULL,
  MaHD NUMBER NOT NULL,
  SoLuong NUMBER DEFAULT 1,
  ThanhTien FLOAT DEFAULT 0
);

CREATE OR REPLACE TRIGGER insert_thanhtien
BEFORE INSERT ON chitiethoadon
FOR EACH ROW
BEGIN
    SELECT (:NEW.SoLuong * h.GiaBan) INTO :NEW.ThanhTien
    FROM hanghoa h
    WHERE h.MaHang = :NEW.MaHang;
END;
/

CREATE OR REPLACE TRIGGER insert_tongtien
FOR INSERT ON chitiethoadon
COMPOUND TRIGGER

    -- Define a collection to store the MaHD values
    TYPE MaHD_TableType IS TABLE OF chitiethoadon.MaHD%TYPE;
    MaHD_Table MaHD_TableType := MaHD_TableType();

    -- Statement-level trigger to gather MaHD values
    AFTER EACH ROW IS
    BEGIN
        MaHD_Table.EXTEND;
        MaHD_Table(MaHD_Table.LAST) := :NEW.MaHD;
    END AFTER EACH ROW;

    -- Row-level trigger to update TongTien
    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1..MaHD_Table.COUNT LOOP
            UPDATE hoadon h
            SET h.TongTien = (SELECT NVL(SUM(ThanhTien), 0) FROM chitiethoadon WHERE MaHD = MaHD_Table(i))
            WHERE h.MaHD = MaHD_Table(i);
        END LOOP;
    END AFTER STATEMENT;

END insert_tongtien;
/

CREATE OR REPLACE TRIGGER insert_chitiethoadon
AFTER INSERT ON chitiethoadon
FOR EACH ROW
BEGIN
    UPDATE hanghoa h
    SET h.SoLuongTon = h.SoLuongTon - :NEW.SoLuong
    WHERE h.MaHang = :NEW.MaHang;
END;
/

INSERT ALL
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (1, 1, 2, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (11, 2, 3, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (12, 2, 3, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (13, 3, 2, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (14, 3, 5, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (15, 4, 2, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (16, 4, 4, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (23, 1, 2, 0)
    INTO chitiethoadon (MaHang, MaHD, SoLuong, ThanhTien) VALUES (36, 2, 3, 0)
SELECT * FROM dual;

CREATE TABLE phieunhap (
  MaPN NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  MaNV NUMBER NOT NULL,
  MaNCC NUMBER NOT NULL,
  NgayNhap DATE DEFAULT SYSDATE,
  TongTien FLOAT NOT NULL,
  TrangThai NVARCHAR2(50) DEFAULT 'Đã nhập hàng'
);

INSERT INTO phieunhap (MaNV, MaNCC, TongTien) VALUES
(1, 1, 2000000);

CREATE TABLE chitietphieunhap (
  MaPN NUMBER NOT NULL,
  MaHang NUMBER NOT NULL,
  GiaNhap NUMBER NOT NULL,
  SoLuong NUMBER DEFAULT 10,
  ThanhTien NUMBER DEFAULT 0
);

CREATE OR REPLACE TRIGGER tinh_thanh_tien_ctpn
BEFORE INSERT ON chitietphieunhap
FOR EACH ROW
BEGIN
    -- Tính toán giá tr? m?i c?a ThanhTien và c?p nh?t
    :NEW.ThanhTien := :NEW.GiaNhap * :NEW.SoLuong;
END;
/

CREATE OR REPLACE TRIGGER tinh_tong_tien_phieunhap
FOR INSERT ON chitietphieunhap
COMPOUND TRIGGER

    -- Define a collection to store the MaPN values
    TYPE MaPN_TableType IS TABLE OF chitietphieunhap.MaPN%TYPE;
    MaPN_Table MaPN_TableType := MaPN_TableType();

    -- Statement-level trigger to gather MaPN values
    AFTER EACH ROW IS
    BEGIN
        MaPN_Table.EXTEND;
        MaPN_Table(MaPN_Table.LAST) := :NEW.MaPN;
    END AFTER EACH ROW;

    -- Row-level trigger to update TongTien
    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1..MaPN_Table.COUNT LOOP
            UPDATE phieunhap
            SET TongTien = (SELECT NVL(SUM(ThanhTien), 0) FROM chitietphieunhap WHERE MaPN = MaPN_Table(i))
            WHERE MaPN = MaPN_Table(i);
        END LOOP;
    END AFTER STATEMENT;

END tinh_tong_tien_phieunhap;
/

CREATE OR REPLACE TRIGGER update_gia_nhap_hanghoa
AFTER INSERT ON chitietphieunhap
FOR EACH ROW
BEGIN
    -- C?p nh?t giá nh?p m?i cho hàng hóa (n?u giá nh?p m?i l?n h?n giá nh?p hi?n t?i)
    UPDATE hanghoa
    SET GiaNhap = :NEW.GiaNhap
    WHERE MaHang = :NEW.MaHang
    AND GiaNhap < :NEW.GiaNhap;
END;
/

CREATE OR REPLACE TRIGGER update_so_luongton_ctpn
AFTER INSERT ON chitietphieunhap
FOR EACH ROW
BEGIN
    -- C?p nh?t s? l??ng t?n c?a hàng hóa
    UPDATE hanghoa
    SET SoLuongTon = SoLuongTon + :NEW.SoLuong
    WHERE MaHang = :NEW.MaHang;
END;
/


INSERT ALL
    INTO chitietphieunhap (MaPN, MaHang, GiaNhap, SoLuong, ThanhTien) VALUES (1, 1, 12500, 4, 0)
    INTO chitietphieunhap (MaPN, MaHang, GiaNhap, SoLuong, ThanhTien) VALUES (1, 3, 50000, 5, 0)
    INTO chitietphieunhap (MaPN, MaHang, GiaNhap, SoLuong, ThanhTien) VALUES (1, 6, 12000, 5, 0)
    INTO chitietphieunhap (MaPN, MaHang, GiaNhap, SoLuong, ThanhTien) VALUES (1, 12, 8000, 5, 0)
    INTO chitietphieunhap (MaPN, MaHang, GiaNhap, SoLuong, ThanhTien) VALUES (1, 15, 8000, 5, 0)
SELECT * FROM dual;

CREATE TABLE khachhang (
  MaKH NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  TenKH NVARCHAR2(50) NOT NULL,
  SDT NVARCHAR2(30) DEFAULT 'Chưa xác đinh',
  DiaChi NVARCHAR2(50) DEFAULT 'Chưa xác đinh',
  TrangThai NUMBER DEFAULT 1
);

INSERT    INTO khachhang (TenKH, SDT, DiaChi) VALUES (N'Nguyễn Văn Phú', '0987654321', N'Lê Trọng Tấn');
INSERT    INTO khachhang (TenKH, SDT, DiaChi) VALUES (N'Trần Thị Dung', '0123456789', N'Bình Chánh');
INSERT    INTO khachhang (TenKH, SDT, DiaChi) VALUES (N'Lê Văn Sỹ', '0912345678', N'Lạc Long Quân');
INSERT    INTO khachhang (TenKH, SDT, DiaChi) VALUES (N'Phạm Thị Kim', '0876543210', N'Thành Thái');
INSERT    INTO khachhang (TenKH, SDT, DiaChi) VALUES (N'Hoàng Văn Cường', '0965432187', N'Điện Biên Phủ');

CREATE TABLE nhacungcap (
  MaNCC NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  TenNCC NVARCHAR2(50) NOT NULL,
  SDT NVARCHAR2(30) DEFAULT 'Chưa xác đinh',
  DiaChi NVARCHAR2(50) DEFAULT 'Chưa xác đinh',
  TrangThai NUMBER DEFAULT 1
);

INSERT INTO nhacungcap (TenNCC, SDT, DiaChi) VALUES (N'LangFarm', '0765486382', N'Bình Thạnh');
INSERT INTO nhacungcap (TenNCC, SDT, DiaChi) VALUES (N'Nông sản Nguyên Vy', '0765486383', N'Lâm Đồng');
INSERT INTO nhacungcap (TenNCC, SDT, DiaChi) VALUES (N'SUNRISE INS', '0765486384', 'Tp.HCM');
INSERT INTO nhacungcap (TenNCC, SDT, DiaChi) VALUES (N'Thành Nam', '0765486385', N'Bình Dương');
INSERT INTO nhacungcap (TenNCC, SDT, DiaChi) VALUES (N'Nam Đô', '0765486386', N'Đà Nẵng');

CREATE TABLE nhanvien (
  MaNV NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  TenNV NVARCHAR2(50) NOT NULL,
  SDT NVARCHAR2(30) DEFAULT 'Chưa xác đinh',
  UserName NVARCHAR2(30) NOT NULL,
  Password NVARCHAR2(30) NOT NULL,
  ChucVu NVARCHAR2(50) DEFAULT 'Nhân viên',
  DiaChi NVARCHAR2(50) DEFAULT 'Chưa xác định',
  TrangThai NUMBER DEFAULT 1
);

INSERT INTO nhanvien (TenNV, SDT, UserName, Password, ChucVu, DiaChi) VALUES (N'Nguyễn Văn Bình', '0897785658', 'admin', 'admin123', N'Quản lý', 'TPHCM');
INSERT INTO nhanvien (TenNV, SDT, UserName, Password, ChucVu, DiaChi) VALUES (N'Hồ Văn Cường', '0897785623', 'cuong', '123', N'Nhân viên', 'TPHCM');
INSERT INTO nhanvien (TenNV, SDT, UserName, Password, ChucVu, DiaChi) VALUES (N'Trương Thị Tuyết Linh', '0897785612', 'linh', '123', N'Nhân viên', 'TPHCM');
INSERT INTO nhanvien (TenNV, SDT, UserName, Password, ChucVu, DiaChi) VALUES (N'Võ Văn Minh', '0897785123', 'minh', '123', N'Nhân viên', 'TPHCM');


CREATE TABLE nhomhang (
  MaNhomHang NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  TenNhomHang NVARCHAR2(50) NOT NULL,
  TrangThai NUMBER DEFAULT 1
);

INSERT    INTO nhomhang (TenNhomHang) VALUES (N'Rau');
INSERT    INTO nhomhang (TenNhomHang) VALUES (N'Củ');
INSERT    INTO nhomhang (TenNhomHang) VALUES (N'Nấm');
INSERT    INTO nhomhang (TenNhomHang) VALUES (N'Trái cây');

ALTER TABLE nhanvien
  ADD CONSTRAINT UQ_NhanVien_UserName UNIQUE (UserName);
ALTER TABLE nhacungcap
  ADD CONSTRAINT UQ_NhaCungCap_TenNCC UNIQUE (TenNCC);
ALTER TABLE hanghoa
  ADD CONSTRAINT UQ_HangHoa_TenHang UNIQUE (TenHang);
ALTER TABLE nhomhang
  ADD CONSTRAINT UQ_NhomHang_TenNhomHang UNIQUE (TenNhomHang);
ALTER TABLE hanghoa
  ADD CONSTRAINT FK_HangHoa_NhomHang FOREIGN KEY (MaNhomHang) REFERENCES nhomhang (MaNhomHang);
ALTER TABLE hanghoa
  ADD CONSTRAINT FK_HangHoa_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES nhacungcap (MaNCC);

ALTER TABLE hoadon
  ADD CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES nhanvien (MaNV);
ALTER TABLE hoadon
  ADD CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES khachhang (MaKH);

ALTER TABLE phieunhap
  ADD CONSTRAINT FK_PhieuNhap_NhanVien FOREIGN KEY (MaNV) REFERENCES nhanvien (MaNV);
ALTER TABLE phieunhap
  ADD CONSTRAINT FK_PhieuNhap_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES nhacungcap (MaNCC);
ALTER TABLE chitiethoadon
  ADD CONSTRAINT PK_ChiTietHoaDon PRIMARY KEY (MaHang, MaHD);
ALTER TABLE chitiethoadon
  ADD CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHD) REFERENCES hoadon (MaHD);
ALTER TABLE chitiethoadon
  ADD CONSTRAINT FK_ChiTietHoaDon_HangHoa FOREIGN KEY (MaHang) REFERENCES HangHoa (MaHang);
ALTER TABLE chitietphieunhap
  ADD CONSTRAINT PK_ChiTietPhieuNhap PRIMARY KEY (MaPN, MaHang);
ALTER TABLE chitietphieunhap
  ADD CONSTRAINT FK_ChiTietPhieuNhap_MaHang FOREIGN KEY (MaHang) REFERENCES hanghoa (MaHang);
ALTER TABLE chitietphieunhap
  ADD CONSTRAINT FK_ChiTietPhieuNhap_PhieuNhap FOREIGN KEY (MaPN) REFERENCES PhieuNhap (MaPN);

 -- Store procedure on table HangHoa
 -- Update HangHoa
CREATE OR REPLACE PROCEDURE UpdateHangHoa (
    MaHang IN NUMBER,
    MaNhomHang IN NUMBER,
    MaNCC IN NUMBER,
    TenHang IN NVARCHAR2,
    DVT IN NVARCHAR2,
    GiaNhap IN FLOAT,
    HeSo IN FLOAT,
    HinhAnh IN NVARCHAR2,
    SoLuongTon IN FLOAT,
    TrangThai IN NUMBER
)
IS
BEGIN
    UPDATE hanghoa
    SET MaNhomHang = UpdateHangHoa.MaNhomHang,
        MaNCC = UpdateHangHoa.MaNCC,
        TenHang = UpdateHangHoa.TenHang,
        DVT = UpdateHangHoa.DVT,
        GiaNhap = UpdateHangHoa.GiaNhap,
        HeSo = UpdateHangHoa.HeSo,
        SoLuongTon = UpdateHangHoa.SoLuongTon,
        HinhAnh = UpdateHangHoa.HinhAnh,
        TrangThai = UpdateHangHoa.TrangThai
    WHERE MaHang = UpdateHangHoa.MaHang;
    COMMIT;
END UpdateHangHoa;
/

CREATE OR REPLACE PROCEDURE InsertHangHoa (
    MaNhomHang IN NUMBER,
    MaNCC IN NUMBER,
    TenHang IN NVARCHAR2,
    DVT IN NVARCHAR2,
    GiaNhap IN FLOAT,
    HeSo IN FLOAT,
    HinhAnh IN NVARCHAR2,
    SoLuongTon IN FLOAT,
    TrangThai IN NUMBER
)
IS
BEGIN
    INSERT INTO hanghoa (MaNhomHang, MaNCC, TenHang, DVT, GiaNhap, HeSo, HinhAnh, SoLuongTon, TrangThai)
    VALUES (InsertHangHoa.MaNhomHang, InsertHangHoa.MaNCC, InsertHangHoa.TenHang, InsertHangHoa.DVT, InsertHangHoa.GiaNhap,
            InsertHangHoa.HeSo, InsertHangHoa.HinhAnh, InsertHangHoa.SoLuongTon, InsertHangHoa.TrangThai);
    COMMIT;
END InsertHangHoa;
/

