/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import GUI.DangNhapJDialog;
import Main.DanhMucBean;
import Main.ScreenSwitch;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class AdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();
        setTitle("QUẢN TRỊ CƠ SỞ DỮ LIỆU ORACLE");

        ScreenSwitch controller = new ScreenSwitch(jpnView);
        controller.setView(jpnInfoDB, jlbInfoDB, "InfoDB");

        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("InfoDB", jpnInfoDB, jlbInfoDB));
        listItem.add(new DanhMucBean("Session", jpnSession, jlbSession));
        listItem.add(new DanhMucBean("Tablespace", jpnTablespace, jlbTablespace));
        listItem.add(new DanhMucBean("User", jpnUser, jlbUser));
        listItem.add(new DanhMucBean("Policy", jpnPolicy, jlbPolicy));
        listItem.add(new DanhMucBean("Permission", jpnPermission, jlbPermission));

        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnName = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jpnInfoDB = new javax.swing.JPanel();
        jlbInfoDB = new javax.swing.JLabel();
        jpnSession = new javax.swing.JPanel();
        jlbSession = new javax.swing.JLabel();
        jpnTablespace = new javax.swing.JPanel();
        jlbTablespace = new javax.swing.JLabel();
        jpnUser = new javax.swing.JPanel();
        jlbUser = new javax.swing.JLabel();
        jpnPolicy = new javax.swing.JPanel();
        jlbPolicy = new javax.swing.JLabel();
        jpnPermission = new javax.swing.JPanel();
        jlbPermission = new javax.swing.JLabel();
        jbtDangXuat = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(102, 102, 102));

        jpnName.setBackground(new java.awt.Color(211, 211, 211));

        jlbName.setBackground(new java.awt.Color(255, 228, 196));
        jlbName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-shop.png"))); // NOI18N
        jlbName.setText("Oracle DB Admin Dashboard");

        javax.swing.GroupLayout jpnNameLayout = new javax.swing.GroupLayout(jpnName);
        jpnName.setLayout(jpnNameLayout);
        jpnNameLayout.setHorizontalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jpnNameLayout.setVerticalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jpnInfoDB.setBackground(new java.awt.Color(211, 211, 211));

        jlbInfoDB.setBackground(new java.awt.Color(255, 255, 255));
        jlbInfoDB.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbInfoDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-home.png"))); // NOI18N
        jlbInfoDB.setText("Thông Tin Database");

        javax.swing.GroupLayout jpnInfoDBLayout = new javax.swing.GroupLayout(jpnInfoDB);
        jpnInfoDB.setLayout(jpnInfoDBLayout);
        jpnInfoDBLayout.setHorizontalGroup(
            jpnInfoDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInfoDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnInfoDBLayout.setVerticalGroup(
            jpnInfoDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbInfoDB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jpnSession.setBackground(new java.awt.Color(211, 211, 211));

        jlbSession.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-sell.png"))); // NOI18N
        jlbSession.setText("Quản Lý Session");

        javax.swing.GroupLayout jpnSessionLayout = new javax.swing.GroupLayout(jpnSession);
        jpnSession.setLayout(jpnSessionLayout);
        jpnSessionLayout.setHorizontalGroup(
            jpnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSessionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnSessionLayout.setVerticalGroup(
            jpnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbSession, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jpnTablespace.setBackground(new java.awt.Color(211, 211, 211));

        jlbTablespace.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbTablespace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-product.png"))); // NOI18N
        jlbTablespace.setText("Quản Lý Tablespace");

        javax.swing.GroupLayout jpnTablespaceLayout = new javax.swing.GroupLayout(jpnTablespace);
        jpnTablespace.setLayout(jpnTablespaceLayout);
        jpnTablespaceLayout.setHorizontalGroup(
            jpnTablespaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTablespaceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTablespace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnTablespaceLayout.setVerticalGroup(
            jpnTablespaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTablespace, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jpnUser.setBackground(new java.awt.Color(211, 211, 211));

        jlbUser.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-category.png"))); // NOI18N
        jlbUser.setText("Quản Lý Users");

        javax.swing.GroupLayout jpnUserLayout = new javax.swing.GroupLayout(jpnUser);
        jpnUser.setLayout(jpnUserLayout);
        jpnUserLayout.setHorizontalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnUserLayout.setVerticalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnPolicy.setBackground(new java.awt.Color(211, 211, 211));

        jlbPolicy.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbPolicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-order.png"))); // NOI18N
        jlbPolicy.setText("Quản Lý Policy");

        javax.swing.GroupLayout jpnPolicyLayout = new javax.swing.GroupLayout(jpnPolicy);
        jpnPolicy.setLayout(jpnPolicyLayout);
        jpnPolicyLayout.setHorizontalGroup(
            jpnPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPolicyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnPolicyLayout.setVerticalGroup(
            jpnPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jpnPermission.setBackground(new java.awt.Color(211, 211, 211));

        jlbPermission.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbPermission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-import.png"))); // NOI18N
        jlbPermission.setText("Quản Lý Permission");

        javax.swing.GroupLayout jpnPermissionLayout = new javax.swing.GroupLayout(jpnPermission);
        jpnPermission.setLayout(jpnPermissionLayout);
        jpnPermissionLayout.setHorizontalGroup(
            jpnPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPermissionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbPermission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnPermissionLayout.setVerticalGroup(
            jpnPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbPermission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jbtDangXuat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtDangXuat.setText("Đăng Xuất");
        jbtDangXuat.setPreferredSize(new java.awt.Dimension(200, 60));
        jbtDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnPermission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnPolicy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnInfoDB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnSession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTablespace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jbtDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jpnInfoDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnTablespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnPermission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jbtDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();

        DangNhapJDialog dialog = new DangNhapJDialog(null, true);
        dialog.setTitle("Đăng Nhập Hệ Thống");
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtDangXuat;
    private javax.swing.JLabel jlbInfoDB;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPermission;
    private javax.swing.JLabel jlbPolicy;
    private javax.swing.JLabel jlbSession;
    private javax.swing.JLabel jlbTablespace;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JPanel jpnInfoDB;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnName;
    private javax.swing.JPanel jpnPermission;
    private javax.swing.JPanel jpnPolicy;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnSession;
    private javax.swing.JPanel jpnTablespace;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
