/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;
import DTO.Admin.Datafile;
import DAO.Admin.DatafileDAO;
import DAO.Admin.TablespaceDAO;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Quang
 */
public class DatafileJFrame extends javax.swing.JFrame {
    ArrayList<Datafile> listDatafile;
    /**
     * Creates new form DatafileJFrame
     */
    public DatafileJFrame(int file_id) {
        initComponents();
        setView(file_id);
    }
    
    public void setView(int file_id) {
        listDatafile = DatafileDAO.getInstance().getDatafileByID(file_id);
        if(listDatafile != null) {
            String[] header = {"File name","File id","Tablespace name"};
            DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return false;
                }
            };

            for (Datafile dt : listDatafile) {
                Object[] row = {dt.getFile_name(), dt.getFile_id(), dt.getTablespace_name()};
                modelTableDb.addRow(row);
            }

            TableRowSorter<TableModel> rowSorter = null;            


            jtDatafile.setModel(modelTableDb);
            jtDatafile.setRowSorter(rowSorter);

            jtDatafile.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
            jtDatafile.setFont(new Font("Arial", Font.PLAIN, 14));
            jtDatafile.getTableHeader().setPreferredSize(new Dimension(100, 50));
            jtDatafile.setRowHeight(50);
            jtDatafile.validate();
            jtDatafile.repaint();

            jspDatafile.setPreferredSize(new Dimension(1350, 400));

            jpnView.removeAll();
            jpnView.setLayout(new CardLayout());
            jpnView.add(jspDatafile);
            jpnView.validate();
            jpnView.repaint();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbDatafile = new javax.swing.JTabbedPane();
        jpnInfoDatafile = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jspDatafile = new javax.swing.JScrollPane();
        jtDatafile = new javax.swing.JTable();
        jbtnThem = new javax.swing.JButton();
        jtfTablespaceName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbDatafile.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jtDatafile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspDatafile.setViewportView(jtDatafile);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jspDatafile, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspDatafile, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        jbtnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnThem.setText("Thêm tablespace");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên tablespace");

        javax.swing.GroupLayout jpnInfoDatafileLayout = new javax.swing.GroupLayout(jpnInfoDatafile);
        jpnInfoDatafile.setLayout(jpnInfoDatafileLayout);
        jpnInfoDatafileLayout.setHorizontalGroup(
            jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTablespaceName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnInfoDatafileLayout.setVerticalGroup(
            jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                            .addComponent(jtfTablespaceName)
                            .addGap(1, 1, 1)))
                    .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbDatafile.addTab("Thông tin chi tiết Datafile", jpnInfoDatafile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jtbDatafile)
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jtbDatafile)
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        // TODO add your handling code here:
        try {
            int index = jtDatafile.getSelectedRow();
            Datafile dtf = listDatafile.get(index);

            String file_name = dtf.getFile_name();            
            String tablespace_name = jtfTablespaceName.getText();
            Integer file_id = dtf.getFile_id();
            
            TablespaceDAO.getInstance().createTablespace(tablespace_name, file_name);    
            JOptionPane.showMessageDialog(null, "Tạo tablespace thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            setView(file_id);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn datafile muốn tạo tablespace!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JPanel jpnInfoDatafile;
    private javax.swing.JPanel jpnView;
    private javax.swing.JScrollPane jspDatafile;
    private javax.swing.JTable jtDatafile;
    private javax.swing.JTabbedPane jtbDatafile;
    private javax.swing.JTextField jtfTablespaceName;
    // End of variables declaration//GEN-END:variables
}
