/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;
import DAO.Admin.DatafileDAO;
import DAO.Admin.TablespaceDAO;
import DTO.Admin.Datafile;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Quang
 */
public class DatafileJPanel extends javax.swing.JPanel {
    ArrayList<Datafile> listDatafile;
    /**
     * Creates new form DatafileJPanel
     */
    public DatafileJPanel() {
        initComponents();
    }

    public void loadDatafile() {
        String[] header = {"File name","File id"};
        listDatafile = DatafileDAO.getInstance().getAllDatafile();
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        for (Datafile dt : listDatafile) {
            Object[] row = {dt.getFile_name(), dt.getFile_id()};
            modelTableDb.addRow(row);
        }
        
        TableRowSorter<TableModel> rowSorter = null;
        jlbSoLuongDatafile.setText("Số lượng datafile: ");
        String txtSoLuongDatafile = jlbSoLuongDatafile.getText() + listDatafile.size();
        jlbSoLuongDatafile.setText(txtSoLuongDatafile);
        
        jtDatafile.setModel(modelTableDb);
        jtDatafile.setRowSorter(rowSorter);

        jtDatafile.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jtDatafile.setFont(new Font("Arial", Font.PLAIN, 14));
        jtDatafile.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jtDatafile.setRowHeight(50);
        jtDatafile.validate();
        jtDatafile.repaint();

        jspDatafile.setPreferredSize(new Dimension(1350, 400));

        jpnView.removeAll();
        jpnView.setLayout(new CardLayout());
        jpnView.add(jspDatafile);
        jpnView.validate();
        jpnView.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbDatafile = new javax.swing.JTabbedPane();
        jpnInfoDatafile = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jspDatafile = new javax.swing.JScrollPane();
        jtDatafile = new javax.swing.JTable();
        jlbSoLuongDatafile = new javax.swing.JLabel();

        jtbDatafile.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtbDatafile.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbDatafileStateChanged(evt);
            }
        });

        jtDatafile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtDatafile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDatafileMouseClicked(evt);
            }
        });
        jspDatafile.setViewportView(jtDatafile);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jspDatafile, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspDatafile, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jlbSoLuongDatafile.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbSoLuongDatafile.setText("Số lượng datafile: ");

        javax.swing.GroupLayout jpnInfoDatafileLayout = new javax.swing.GroupLayout(jpnInfoDatafile);
        jpnInfoDatafile.setLayout(jpnInfoDatafileLayout);
        jpnInfoDatafileLayout.setHorizontalGroup(
            jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                        .addComponent(jlbSoLuongDatafile)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnInfoDatafileLayout.setVerticalGroup(
            jpnInfoDatafileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoDatafileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSoLuongDatafile)
                .addGap(38, 38, 38)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbDatafile.addTab("Thông tin Datafile", jpnInfoDatafile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbDatafile)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbDatafile)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtDatafileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDatafileMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && jtDatafile.getSelectedRow() != -1) {
            int index = jtDatafile.getSelectedRow();

            Datafile dtf = listDatafile.get(index);

            int file_id = dtf.getFile_id();

            DatafileJFrame frame = new DatafileJFrame(file_id);
            frame.setResizable(false);

            JDialog dialog = new JDialog();

            dialog.setModal(true);
            dialog.getContentPane().add(frame.getContentPane());
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setTitle("Thông tin chi tiết Datafile");
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jtDatafileMouseClicked

    private void jtbDatafileStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbDatafileStateChanged
        // TODO add your handling code here:
        int index = jtbDatafile.getSelectedIndex();
        if (index == 0) {
            loadDatafile();
        }
    }//GEN-LAST:event_jtbDatafileStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbSoLuongDatafile;
    private javax.swing.JPanel jpnInfoDatafile;
    private javax.swing.JPanel jpnView;
    private javax.swing.JScrollPane jspDatafile;
    private javax.swing.JTable jtDatafile;
    private javax.swing.JTabbedPane jtbDatafile;
    // End of variables declaration//GEN-END:variables
}
