/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.Admin.SGADAO;
import DAO.HangHoaDAO;
import DTO.Admin.TableData;
import DTO.HangHoa;
import GUI.HangHoaJFrame;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class InfoDBJPanel extends javax.swing.JPanel {

    ArrayList<TableData> listSGA;

    /**
     * Creates new form InfoDBJPanel
     */
    public InfoDBJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbSGA = new javax.swing.JTabbedPane();
        jpnSGA = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jspSGA = new javax.swing.JScrollPane();
        jtSGA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpnPGA = new javax.swing.JPanel();
        jpnView1 = new javax.swing.JPanel();
        jspPGA = new javax.swing.JScrollPane();
        jtPGA = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jpnProcess = new javax.swing.JPanel();
        jpnView2 = new javax.swing.JPanel();
        jspProcess = new javax.swing.JScrollPane();
        jtProcess = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jtbSGA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtbSGA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbSGAStateChanged(evt);
            }
        });

        jtSGA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtSGA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSGAMouseClicked(evt);
            }
        });
        jspSGA.setViewportView(jtSGA);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jspSGA, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspSGA, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN SYSTEM GLOBAL AREA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnSGALayout = new javax.swing.GroupLayout(jpnSGA);
        jpnSGA.setLayout(jpnSGALayout);
        jpnSGALayout.setHorizontalGroup(
            jpnSGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSGALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnSGALayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSGALayout.setVerticalGroup(
            jpnSGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSGALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbSGA.addTab("SGA", jpnSGA);

        jtPGA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPGA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPGAMouseClicked(evt);
            }
        });
        jspPGA.setViewportView(jtPGA);

        javax.swing.GroupLayout jpnView1Layout = new javax.swing.GroupLayout(jpnView1);
        jpnView1.setLayout(jpnView1Layout);
        jpnView1Layout.setHorizontalGroup(
            jpnView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnView1Layout.createSequentialGroup()
                .addComponent(jspPGA, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnView1Layout.setVerticalGroup(
            jpnView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspPGA, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN PROGRAM GLOBAL AREA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnPGALayout = new javax.swing.GroupLayout(jpnPGA);
        jpnPGA.setLayout(jpnPGALayout);
        jpnPGALayout.setHorizontalGroup(
            jpnPGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPGALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnPGALayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPGALayout.setVerticalGroup(
            jpnPGALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPGALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbSGA.addTab("PGA", jpnPGA);

        jtProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProcessMouseClicked(evt);
            }
        });
        jspProcess.setViewportView(jtProcess);

        javax.swing.GroupLayout jpnView2Layout = new javax.swing.GroupLayout(jpnView2);
        jpnView2.setLayout(jpnView2Layout);
        jpnView2Layout.setHorizontalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnView2Layout.createSequentialGroup()
                .addComponent(jspProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnView2Layout.setVerticalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspProcess, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("THÔNG TIN PROCESS");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnProcessLayout = new javax.swing.GroupLayout(jpnProcess);
        jpnProcess.setLayout(jpnProcessLayout);
        jpnProcessLayout.setHorizontalGroup(
            jpnProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnProcessLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnProcessLayout.setVerticalGroup(
            jpnProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProcessLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbSGA.addTab("Process", jpnProcess);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbSGA)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtbSGA)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
 void LoadSGAVaoTable() {
        
        String[] header = {"Name", "Value"};
        listSGA = SGADAO.getInstance().getInfo();
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        for (TableData info : listSGA) {
            Object[] row = {info.getName(), info.getValue()};
            modelTableDb.addRow(row);
        }
        
        TableRowSorter<TableModel> rowSorter = null;
        
        
        jtSGA.setModel(modelTableDb);
        jtSGA.setRowSorter(rowSorter);

        jtSGA.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jtSGA.setFont(new Font("Arial", Font.PLAIN, 14));
        jtSGA.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jtSGA.setRowHeight(50);
        jtSGA.validate();
        jtSGA.repaint();

        jspSGA.setPreferredSize(new Dimension(1350, 400));

        jpnView.removeAll();
        jpnView.setLayout(new CardLayout());
        jpnView.add(jspSGA);
        jpnView.validate();
        jpnView.repaint();
    }
    private void jtbSGAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbSGAStateChanged
        // TODO add your handling code here:
        int index = jtbSGA.getSelectedIndex();
        if (index == 0) {
            LoadSGAVaoTable();
        } else {
            LoadSGAVaoTable();
        }
    }//GEN-LAST:event_jtbSGAStateChanged

    private void jtPGAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPGAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPGAMouseClicked

    private void jtProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProcessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtProcessMouseClicked

    private void jtSGAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSGAMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && jtSGA.getSelectedRow() != -1) {
            //            int index = jtHangHoa.getSelectedRow();
            //
            //            HangHoa hangHoa = listHH.get(index);
            //
            //            HangHoaJFrame frame = new HangHoaJFrame(hangHoa, this, 0);
            //            frame.setResizable(false);
            //
            //            JDialog dialog = new JDialog();
            //            dialog.setModal(true);
            //            dialog.getContentPane().add(frame.getContentPane());
            //            dialog.pack();
            //            dialog.setLocationRelativeTo(null);
            //            dialog.setTitle("Sửa hàng hóa");
            //            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jtSGAMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnPGA;
    private javax.swing.JPanel jpnProcess;
    private javax.swing.JPanel jpnSGA;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnView1;
    private javax.swing.JPanel jpnView2;
    private javax.swing.JScrollPane jspPGA;
    private javax.swing.JScrollPane jspProcess;
    private javax.swing.JScrollPane jspSGA;
    private javax.swing.JTable jtPGA;
    private javax.swing.JTable jtProcess;
    private javax.swing.JTable jtSGA;
    private javax.swing.JTabbedPane jtbSGA;
    // End of variables declaration//GEN-END:variables
}
