/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.Admin.PermissionDAO;
import DAO.Admin.UserDAO;
import DAO.TaiKhoanDAO;
import DTO.Admin.Permission;
import DTO.Admin.User;
import DTO.NhanVien;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class PermissionJPanel extends javax.swing.JPanel {

    ArrayList<Permission> listPermission;
    ArrayList<Permission> listUserPermission;    
    private List<String> checkedPermissions = new ArrayList<>();
    
    /**
     * Creates new form PermissionJPanel
     */
    public PermissionJPanel() {
        initComponents();
        loadPrivs();
        loadComboBoxUers();        
    }

    private void loadPrivs()
    {
        String[] header = {"", "QUYỀN"};
        listPermission = PermissionDAO.getInstance().getInfo();
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? Boolean.class : String.class;
            }
            
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                if(jcbEmpName.getSelectedItem() != null)
                {
                    return colIndex == 0;
                }
                return false;
            }
            
        };
        if(!listPermission.isEmpty())
        {
            for (Permission p : listPermission) {
                Object[] row = {false, p.getPrivilege()};
                modelTableDb.addRow(row);
            }            
        }        
        TableRowSorter<TableModel> rowSorter = null;        

        jtPermission.setModel(modelTableDb);
        jtPermission.setRowSorter(rowSorter);

        jtPermission.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jtPermission.setFont(new Font("Arial", Font.PLAIN, 14));
        jtPermission.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jtPermission.setRowHeight(50);
        jtPermission.validate();
        jtPermission.repaint();

        jsPermission.setPreferredSize(new Dimension(700, 400));

        jpnView.removeAll();
        jpnView.setLayout(new CardLayout());
        jpnView.add(jsPermission);
        jpnView.validate();
        jpnView.repaint();
    }
    private void loadUserPrivs()
    {
        String[] header = {"NHÂN VIÊN", "QUYỀN"};
        if (jcbEmpName.getSelectedItem() != null) {
            String username = (String) jcbEmpName.getSelectedItem();
            listUserPermission = PermissionDAO.getInstance().getInfoByUser(username);
            DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {                
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {                    
                    return false;                                        
                }

            };
            if (!listUserPermission.isEmpty()) {
                for (Permission p : listUserPermission) {
                    Object[] row = {p.getGrantee(), p.getPrivilege()};
                    modelTableDb.addRow(row);
                }
            }

            TableRowSorter<TableModel> rowSorter = null;

            jtUserPrivs.setModel(modelTableDb);
            jtUserPrivs.setRowSorter(rowSorter);

            jtUserPrivs.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
            jtUserPrivs.setFont(new Font("Arial", Font.PLAIN, 14));
            jtUserPrivs.getTableHeader().setPreferredSize(new Dimension(100, 50));
            jtUserPrivs.setRowHeight(50);
            jtUserPrivs.validate();
            jtUserPrivs.repaint();

            jsUserPrivs.setPreferredSize(new Dimension(700, 400));

            jpnUserPriv.removeAll();
            jpnUserPriv.setLayout(new CardLayout());
            jpnUserPriv.add(jsUserPrivs);
            jpnUserPriv.validate();
            jpnUserPriv.repaint();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbPermission = new javax.swing.JTabbedPane();
        jpnPriv = new javax.swing.JPanel();
        jcbEmpName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnPhanQuyen = new javax.swing.JButton();
        btnHuyQuyen = new javax.swing.JButton();
        btnXemQuyen = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();
        jsPermission = new javax.swing.JScrollPane();
        jtPermission = new javax.swing.JTable();
        jpnUserPriv = new javax.swing.JPanel();
        jsUserPrivs = new javax.swing.JScrollPane();
        jtUserPrivs = new javax.swing.JTable();
        jpnRole = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfRoleName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jtbPermission.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jcbEmpName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Chọn tên người dùng");

        btnPhanQuyen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPhanQuyen.setText("Phân quyền");
        btnPhanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanQuyenActionPerformed(evt);
            }
        });

        btnHuyQuyen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHuyQuyen.setText("Hủy quyền");
        btnHuyQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyQuyenActionPerformed(evt);
            }
        });

        btnXemQuyen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnXemQuyen.setText("Xem quyền");
        btnXemQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemQuyenActionPerformed(evt);
            }
        });

        jtPermission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPermission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPermissionMouseClicked(evt);
            }
        });
        jsPermission.setViewportView(jtPermission);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsPermission, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsPermission, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jtUserPrivs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtUserPrivs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUserPrivsMouseClicked(evt);
            }
        });
        jsUserPrivs.setViewportView(jtUserPrivs);

        javax.swing.GroupLayout jpnUserPrivLayout = new javax.swing.GroupLayout(jpnUserPriv);
        jpnUserPriv.setLayout(jpnUserPrivLayout);
        jpnUserPrivLayout.setHorizontalGroup(
            jpnUserPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsUserPrivs, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpnUserPrivLayout.setVerticalGroup(
            jpnUserPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsUserPrivs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnPrivLayout = new javax.swing.GroupLayout(jpnPriv);
        jpnPriv.setLayout(jpnPrivLayout);
        jpnPrivLayout.setHorizontalGroup(
            jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrivLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnPrivLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jcbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrivLayout.createSequentialGroup()
                        .addComponent(btnXemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnHuyQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnUserPriv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jpnPrivLayout.setVerticalGroup(
            jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrivLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnPrivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnUserPriv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbPermission.addTab("Quyền", jpnPriv);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên nhóm quyền");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Tạo");

        javax.swing.GroupLayout jpnRoleLayout = new javax.swing.GroupLayout(jpnRole);
        jpnRole.setLayout(jpnRoleLayout);
        jpnRoleLayout.setHorizontalGroup(
            jpnRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRoleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1143, Short.MAX_VALUE))
        );
        jpnRoleLayout.setVerticalGroup(
            jpnRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRoleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpnRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(597, Short.MAX_VALUE))
        );

        jtbPermission.addTab("Nhóm quyền", jpnRole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtbPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 1662, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbPermission, javax.swing.GroupLayout.PREFERRED_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemQuyenActionPerformed
        // TODO add your handling code here:
        if(jcbEmpName.getSelectedItem() != null)
            loadUserPrivs();
        else
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xem quyền" , "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXemQuyenActionPerformed

    private void btnHuyQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyQuyenActionPerformed
        // TODO add your handling code here:
        String username = (String) jcbEmpName.getSelectedItem();
        if(checkedPermissions != null)
        {
            for (String permission : checkedPermissions) {
                PermissionDAO.getInstance().revokeUserPrivilege(username, permission);
                JOptionPane.showMessageDialog(this, "Đã hủy quyền " + permission + " của " + username, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quyền cần thực hiện" , "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHuyQuyenActionPerformed

    private void btnPhanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanQuyenActionPerformed
        // TODO add your handling code here:
        String username = (String) jcbEmpName.getSelectedItem();
        if(checkedPermissions != null)
        {
            for (String permission : checkedPermissions) {
                PermissionDAO.getInstance().grantUserPrivilege(username, permission);
                JOptionPane.showMessageDialog(this, "Đã phân quyền " + permission + " cho " + username, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quyền cần thực hiện" , "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPhanQuyenActionPerformed

    private void jtPermissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPermissionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPermissionMouseClicked

    private void jtUserPrivsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUserPrivsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUserPrivsMouseClicked
    private void loadComboBoxUers()
    {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        List<User> listNV = UserDAO.getInstance().getListUser();

        for (User nv : listNV) {
            model.addElement(nv.getUSERNAME());
        }
        jcbEmpName.setModel(model);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyQuyen;
    private javax.swing.JButton btnPhanQuyen;
    private javax.swing.JButton btnXemQuyen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcbEmpName;
    private javax.swing.JPanel jpnPriv;
    private javax.swing.JPanel jpnRole;
    private javax.swing.JPanel jpnUserPriv;
    private javax.swing.JPanel jpnView;
    private javax.swing.JScrollPane jsPermission;
    private javax.swing.JScrollPane jsUserPrivs;
    private javax.swing.JTable jtPermission;
    private javax.swing.JTable jtUserPrivs;
    private javax.swing.JTabbedPane jtbPermission;
    private javax.swing.JTextField jtfRoleName;
    // End of variables declaration//GEN-END:variables
}
