/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.Admin.PolicyDAO;
import DAO.DataProvider;
import DTO.Admin.Policy;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Main.FontOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Quang
 */
public class PolicyJFrame extends javax.swing.JFrame {
    private PolicyJPanel policyJPanel;
    DataProvider dataProvider = DataProvider.getInstance();
    Connection connection = dataProvider.getConnection();
    /**
     * Creates new form PolicyJFrame
     */
    public PolicyJFrame(Policy policy, PolicyJPanel policyJPanel) {
        initComponents();
        this.policyJPanel = policyJPanel;
        FontOptionPane.setUIFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnThongTinPolicy = new javax.swing.JPanel();
        jlbPCName = new javax.swing.JLabel();
        jtfPolicyName = new javax.swing.JTextField();
        jlbSchemaName = new javax.swing.JLabel();
        jlbStatementType = new javax.swing.JLabel();
        jtfStatementType = new javax.swing.JTextField();
        jtfSchemaName = new javax.swing.JTextField();
        jlbTableName = new javax.swing.JLabel();
        jtfTableName = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnThongTinPolicy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin policy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jpnThongTinPolicy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jlbPCName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbPCName.setText("Tên policy");

        jtfPolicyName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfPolicyName.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jlbSchemaName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbSchemaName.setText("Tên schema");

        jlbStatementType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbStatementType.setText("Các hành động");

        jtfStatementType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jtfSchemaName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfSchemaName.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jlbTableName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbTableName.setText("Tên bảng");

        jtfTableName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfTableName.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jpnThongTinPolicyLayout = new javax.swing.GroupLayout(jpnThongTinPolicy);
        jpnThongTinPolicy.setLayout(jpnThongTinPolicyLayout);
        jpnThongTinPolicyLayout.setHorizontalGroup(
            jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinPolicyLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnThongTinPolicyLayout.createSequentialGroup()
                        .addComponent(jlbStatementType)
                        .addGap(31, 31, 31)
                        .addComponent(jtfStatementType, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnThongTinPolicyLayout.createSequentialGroup()
                        .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbSchemaName)
                            .addComponent(jlbPCName)
                            .addComponent(jlbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSchemaName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 360, Short.MAX_VALUE))
        );
        jpnThongTinPolicyLayout.setVerticalGroup(
            jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinPolicyLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPCName)
                    .addComponent(jtfPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSchemaName)
                    .addComponent(jtfSchemaName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnThongTinPolicyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStatementType)
                    .addComponent(jtfStatementType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        btnLuu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-save.png"))); // NOI18N
        btnLuu.setText("Lưu dữ liệu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(729, Short.MAX_VALUE)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jpnThongTinPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(37, 37, 37)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 466, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jpnThongTinPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String policyName = jtfPolicyName.getText();
        String schemaName = jtfSchemaName.getText();
        String tableName = jtfTableName.getText();
        String StrOperation = jtfStatementType.getText();
        String[] Operation = StrOperation.split(",");
        
        try {
            PolicyDAO.setupAuditPolicy(connection, policyName, schemaName, tableName, Operation);
            JOptionPane.showMessageDialog(this, "Thêm thành công!", "Thêm policy", JOptionPane.INFORMATION_MESSAGE);
            policyJPanel.loadPolicy();
        } catch (SQLException ex) {
            Logger.getLogger(PolicyJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jlbPCName;
    private javax.swing.JLabel jlbSchemaName;
    private javax.swing.JLabel jlbStatementType;
    private javax.swing.JLabel jlbTableName;
    private javax.swing.JPanel jpnThongTinPolicy;
    private javax.swing.JTextField jtfPolicyName;
    private javax.swing.JTextField jtfSchemaName;
    private javax.swing.JTextField jtfStatementType;
    private javax.swing.JTextField jtfTableName;
    // End of variables declaration//GEN-END:variables
}
