/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DAO.Admin.SessionDAO;
import DTO.Admin.Session;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class SessionJPanel extends javax.swing.JPanel {

    ArrayList<Session> listSession;

    /**
     * Creates new form SessionJPanel
     */
    public SessionJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbSession = new javax.swing.JTabbedPane();
        jpnInfoSession = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        jpnView = new javax.swing.JPanel();
        jspSession = new javax.swing.JScrollPane();
        jtSession = new javax.swing.JTable();
        jlbSoLuongSession = new javax.swing.JLabel();

        jtbSession.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtbSession.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbSessionStateChanged(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-delete.png"))); // NOI18N
        btnXoa.setText("Hủy Session");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jtSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSessionMouseClicked(evt);
            }
        });
        jspSession.setViewportView(jtSession);

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(jspSession, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspSession, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jlbSoLuongSession.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbSoLuongSession.setText("Số lượng session: ");

        javax.swing.GroupLayout jpnInfoSessionLayout = new javax.swing.GroupLayout(jpnInfoSession);
        jpnInfoSession.setLayout(jpnInfoSessionLayout);
        jpnInfoSessionLayout.setHorizontalGroup(
            jpnInfoSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnInfoSessionLayout.createSequentialGroup()
                        .addComponent(jlbSoLuongSession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)))
                .addContainerGap())
        );
        jpnInfoSessionLayout.setVerticalGroup(
            jpnInfoSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSoLuongSession))
                .addGap(15, 15, 15)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbSession.addTab("Thông tin session", jpnInfoSession);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jtbSession)
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jtbSession)
                    .addGap(15, 15, 15)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadSession() {
        String[] header = {"SID", "Serial", "Tên người dùng", "Ứng dụng"};
        listSession = SessionDAO.getInstance().getInfo();
        DefaultTableModel modelTableDb = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        for (Session ss : listSession) {
            Object[] row = {ss.getSid(), ss.getSerial(), ss.getUsername(), ss.getProgram()};
            modelTableDb.addRow(row);
        }
        
        TableRowSorter<TableModel> rowSorter = null;
        jlbSoLuongSession.setText("Số lượng session: ");
        String txtSoLuongSession = jlbSoLuongSession.getText() + listSession.size();
        jlbSoLuongSession.setText(txtSoLuongSession);
        
        jtSession.setModel(modelTableDb);
        jtSession.setRowSorter(rowSorter);

        jtSession.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        jtSession.setFont(new Font("Arial", Font.PLAIN, 14));
        jtSession.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jtSession.setRowHeight(50);
        jtSession.validate();
        jtSession.repaint();

        jspSession.setPreferredSize(new Dimension(1350, 400));

        jpnView.removeAll();
        jpnView.setLayout(new CardLayout());
        jpnView.add(jspSession);
        jpnView.validate();
        jpnView.repaint();
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int index = jtSession.getSelectedRow();
            Session session = listSession.get(index);

            int sid = session.getSid();            
            int serial = session.getSerial();
            String username = session.getUsername();

            int kq = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn hủy session của user: " + username + "?", "Câu hỏi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kq == JOptionPane.YES_OPTION) {
                SessionDAO.getInstance().huySession(sid, serial);
            }
            listSession.remove(index);
            loadSession();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng hóa muốn xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void jtbSessionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbSessionStateChanged
        // TODO add your handling code here:
        int index = jtbSession.getSelectedIndex();
        if (index == 0) {
            loadSession();
        } 
    }//GEN-LAST:event_jtbSessionStateChanged

    private void jtSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSessionMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && jtSession.getSelectedRow() != -1) {
            int index = jtSession.getSelectedRow();

            Session session = listSession.get(index);
            
            int sid = session.getSid();

            SessionJFrame frame = new SessionJFrame(sid);
            frame.setResizable(false);

            JDialog dialog = new JDialog();
            
            dialog.setModal(true);
            dialog.getContentPane().add(frame.getContentPane());
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setTitle("Thông tin Process");
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jtSessionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jlbSoLuongSession;
    private javax.swing.JPanel jpnInfoSession;
    private javax.swing.JPanel jpnView;
    private javax.swing.JScrollPane jspSession;
    private javax.swing.JTable jtSession;
    private javax.swing.JTabbedPane jtbSession;
    // End of variables declaration//GEN-END:variables
}
